cabal-version:       3.0
name:                argon
version:             0.4.1.0
synopsis:            Measure your code's complexity
homepage:            http://github.com/rubik/argon
bug-reports:         http://github.com/rubik/argon/issues
license:             ISC
license-file:        LICENSE
author:              Michele Lacchia
maintainer:          michelelacchia@gmail.com
copyright:           2015 Michele Lacchia
category:            Development, Static Analysis
build-type:          Simple
description:
  Argon performs static analysis on your code in order to compute cyclomatic
  complexity. It is a quantitative measure of the number of linearly
  indipendent paths through the code.
  .
  The intended usage is through Argon's executable, which accepts a list of
  files or directories to analyze. The data can be optionally exported to
  JSON.

extra-source-files:
  CHANGELOG.md
  README.md
  stack.yaml
  test/data/*.cabal
  test/data/*.h
  test/data/*.hs
  test/data/include/*.h
  test/tree/*.hs
  test/tree/*.txt
  test/tree/sub/*.hs
  test/tree/sub2/*.hs

common common-extensions
  default-extensions:
    DataKinds
    DerivingStrategies
    DuplicateRecordFields
    LambdaCase
    OverloadedRecordDot

  default-language:   GHC2021

common common-warnings
  ghc-options:
    -Wall -Wcompat -Widentities -Wpartial-fields
    -Wredundant-constraints -fhide-source-paths -fshow-hole-constraints
    -Wunused-packages

library
  import:
    common-warnings
    , common-extensions

  hs-source-dirs:  src
  exposed-modules: Argon
  other-modules:
    Argon.Cabal
    Argon.Formatters
    Argon.Loc
    Argon.Parser
    Argon.Preprocess
    Argon.Results
    Argon.SYB.Utils
    Argon.Types
    Argon.Visitor
    Argon.Walker

  build-depends:
    , aeson
    , ansi-terminal
    , base              >=4.7 && <5
    , Cabal
    , directory
    , ghc
    , ghc-boot
    , ghc-paths
    , Glob
    , microlens
    , pipes
    , pipes-bytestring
    , pipes-group
    , pipes-safe
    , syb

  ghc-options: -threaded

executable argon
  import:
    common-warnings
    , common-extensions

  hs-source-dirs: app
  main-is:        Main.hs
  build-depends:
    , argon
    , base                  >=4.7 && <5
    , optparse-applicative
    , pipes                 >=4.1
    , pipes-safe            >=2.2

  ghc-options:        -threaded -rtsopts -with-rtsopts=-N

test-suite argon-test
  import:
    common-warnings
    , common-extensions

  type:               exitcode-stdio-1.0
  hs-source-dirs:     test
  main-is:            Spec.hs
  other-modules:      ArgonSpec
  build-depends:
    , aeson
    , ansi-terminal
    , argon
    , base           >=4.7 && <5
    , filepath
    , ghc
    , hspec
    , pipes
    , QuickCheck

  build-tool-depends: hspec-discover:hspec-discover >=2 && <3
  ghc-options:        -threaded -rtsopts -with-rtsopts=-N

source-repository head
  type:     git
  location: https://github.com/rubik/argon
